id: P007951
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6609
  title: ཐཱན་ཉུང་གི་འཚོ་བ།
  author: ''
  volumes:
    7e6d1fdd26c041a0a4db32ec14af046e:
      image_group_id: I3CN6611
      title: ''
      volume_number: 1
      total_pages: 114
ebook_metadata:
  title: ཐཱན་ཉུང་གི་འཚོ་བ།
  author: ''
  sku: P007951
  cover: cover.jpg
  layers:
  - pagination
