id: IC8CC1C31
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:29:09+00:00'
last_modified: '2022-06-09T07:54:53.593450+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6609
  title: ཐཱན་ཉུང་གི་འཚོ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8F64:
      image_group_id: I3CN6611
      title: Volume 1 of thAn nyung gi 'tsho ba/
      total_pages: 114
      order: 1
      base_file: 8F64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
